[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Prevent crashes on getting stake sticker
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "for k, v in pairs(G.P_JOKER_RARITY_POOLS[4]) do"
position = "after"
payload = "if type(v) == 'table' and v.key then"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "r_tally = r_tally + 1"
position = "after"
payload = "end"
match_indent = true

# Draw second layer for Castle, etc.
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center:draw_shader('negative', nil, self.ARGS.send_to_shader)"
position = "after"
payload = "if self.children.center2 then self.children.center2:draw_shader('negative', nil, self.ARGS.send_to_shader, nil, self.children.center) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center:draw_shader('foil', nil, self.ARGS.send_to_shader)"
position = "after"
payload = "if self.children.center2 then self.children.center2:draw_shader('foil', nil, self.ARGS.send_to_shader, nil, self.children.center) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center:draw_shader('holo', nil, self.ARGS.send_to_shader)"
position = "after"
payload = "if self.children.center2 then self.children.center2:draw_shader('holo', nil, self.ARGS.send_to_shader, nil, self.children.center) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center:draw_shader('polychrome', nil, self.ARGS.send_to_shader)"
position = "after"
payload = "if self.children.center2 then self.children.center2:draw_shader('polychrome', nil, self.ARGS.send_to_shader, nil, self.children.center) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center:draw_shader('dissolve')"
position = "after"
payload = "if self.children.center2 then self.children.center2:draw_shader('dissolve', nil, nil, nil, self.children.center) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "for k, v in pairs(self.children) do"
position = "after"
payload = "if k ~= 'center2' then"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if (layer == 'card' or layer == 'both') and self.area == G.hand then"
position = "before"
payload = "end"
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "G.shared_shadow = self.sprite_facing == 'front' and self.children.center or self.children.back"
position = "before"
payload = "end"
match_indent = true